### ISSUE TITLE
Problem when I try to compile for WEMOS D1 (ESP8266)

### ISSUE THREAD

**Issue by romildodcm** [DFRobot/DFRobot_SHT20#3]
Hi,
When I try to compile the examples for Wemos D1 mini (a ESP8266 based board) the Arduino IDE report the following error:

Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "LOLIN(WEMOS) D1 mini Pro, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 16MB (FS:14MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

```
C:\Users\Documents\Arduino\libraries\uFire_SHT20\src\uFire_SHT20_MP.cpp:1:18: error: missing binary operator before token "("
 
#if __has_include("ArduinoJson.h")
 
                   ^
 
C:\Users\Documents\Arduino\libraries\uFire_SHT20\src\uFire_SHT20_JSON.cpp:1:18: error: missing binary operator before token "("
 
  #if __has_include("ArduinoJson.h")
 
                   ^
 
exit status 1

Error compiling for board LOLIN(WEMOS) D1 mini Pro.
```

**Comment by ktannady** [comment]
i think ur using wrong library sir..

**Comment by romildodcm** [comment]
Truth! Sorry for the issue. DFRobot_SHT20 really worked, the other not work.
